tasks:
  - name: download-models
    description: Download ONNX models required for building and testing
    command: |
      mkdir -p models
      cd models
      curl -L --output ppocrv4_mobile_det.onnx https://github.com/GreatV/oar-ocr/releases/download/v0.1.0/ppocrv4_mobile_det.onnx
      curl -L --output en_ppocrv4_mobile_rec.onnx https://github.com/GreatV/oar-ocr/releases/download/v0.1.0/en_ppocrv4_mobile_rec.onnx
      echo "Downloaded ONNX models to models/ directory"
  - name: install-hooks
    description: Install git pre-push hook for cargo fmt, test, and clippy
    command: bash install-hooks.sh
